// automatically generated by the FlatBuffers compiler, do not modify

package io.crossbar.crossbarfxmarkets.schema.network;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CellularScan extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static CellularScan getRootAsCellularScan(ByteBuffer _bb) { return getRootAsCellularScan(_bb, new CellularScan()); }
  public static CellularScan getRootAsCellularScan(ByteBuffer _bb, CellularScan obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CellularScan __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int scan(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int scanLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector scanVector() { return scanVector(new ByteVector()); }
  public ByteVector scanVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer scanAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer scanInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long started() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createCellularScan(FlatBufferBuilder builder,
      int scanOffset,
      long started) {
    builder.startTable(2);
    CellularScan.addStarted(builder, started);
    CellularScan.addScan(builder, scanOffset);
    return CellularScan.endCellularScan(builder);
  }

  public static void startCellularScan(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addScan(FlatBufferBuilder builder, int scanOffset) { builder.addOffset(0, scanOffset, 0); }
  public static int createScanVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createScanVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startScanVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addStarted(FlatBufferBuilder builder, long started) { builder.addLong(1, started, 0L); }
  public static int endCellularScan(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CellularScan get(int j) { return get(new CellularScan(), j); }
    public CellularScan get(CellularScan obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

