// automatically generated by the FlatBuffers compiler, do not modify

package io.crossbar.crossbarfxmarkets.schema.network;

/**
 * Cellular signal strength (abstract).
 * See also: https://developer.android.com/reference/android/telephony/CellSignalStrength#summary
 */
public final class CellularSignalStrength {
  private CellularSignalStrength() { }
  public static final byte SIGNAL_STRENGTH_NONE = 0;
  public static final byte SIGNAL_STRENGTH_GOOD = 1;
  public static final byte SIGNAL_STRENGTH_GREAT = 2;
  public static final byte SIGNAL_STRENGTH_MODERATE = 3;
  public static final byte SIGNAL_STRENGTH_NONE_OR_UNKNOWN = 4;
  public static final byte SIGNAL_STRENGTH_POOR = 5;

  public static final String[] names = { "SIGNAL_STRENGTH_NONE", "SIGNAL_STRENGTH_GOOD", "SIGNAL_STRENGTH_GREAT", "SIGNAL_STRENGTH_MODERATE", "SIGNAL_STRENGTH_NONE_OR_UNKNOWN", "SIGNAL_STRENGTH_POOR", };

  public static String name(int e) { return names[e]; }
}

