// automatically generated by the FlatBuffers compiler, do not modify

package io.crossbar.crossbarfxmarkets.schema.network;

public final class IcmpReplyStatus {
  private IcmpReplyStatus() { }
  public static final byte ICMP_REPLY_NONE = 0;
  public static final byte ICMP_REPLY_SUCCESS = 1;
  public static final byte ICMP_REPLY_UNREACHABLE = 2;

  public static final String[] names = { "ICMP_REPLY_NONE", "ICMP_REPLY_SUCCESS", "ICMP_REPLY_UNREACHABLE", };

  public static String name(int e) { return names[e]; }
}

