// automatically generated by the FlatBuffers compiler, do not modify

package io.crossbar.crossbarfxmarkets.schema.network;

/**
 * Wifi channel widths.
 */
public final class WifiChannelWidth {
  private WifiChannelWidth() { }
  public static final byte CHANNEL_WIDTH_NONE = 0;
  public static final byte CHANNEL_WIDTH_20MHZ = 1;
  public static final byte CHANNEL_WIDTH_40MHZ = 2;
  public static final byte CHANNEL_WIDTH_80MHZ = 3;
  public static final byte CHANNEL_WIDTH_160MHZ = 4;
  public static final byte CHANNEL_WIDTH_80MHZ_PLUS_MHZ = 5;

  public static final String[] names = { "CHANNEL_WIDTH_NONE", "CHANNEL_WIDTH_20MHZ", "CHANNEL_WIDTH_40MHZ", "CHANNEL_WIDTH_80MHZ", "CHANNEL_WIDTH_160MHZ", "CHANNEL_WIDTH_80MHZ_PLUS_MHZ", };

  public static String name(int e) { return names[e]; }
}

